using UnityEngine;
using System.Collections;
//including some .NET for dynamic arrays called List in C#
using System.Collections.Generic;

//directives to enforce that our parent Game Object required components
[RequireComponent(typeof(CharacterController))]
[RequireComponent(typeof(Steering))]

public class Villager : MonoBehaviour
{
	// Each vehicle contains a CharacterController which
	// makes it easier to deal with the relationship between
	// movement initiated by the character and the forces
	// generated by contact with the terrain & other game objects.
	private CharacterController characterController;
	private Steering steering;
	private GameManager gameManager;
	
	//wander varables
	public int _wanAngle;
	public int radiusOfCircle;
	public int _wanChange;
	
	//follower reference for deletion
	private Follow follower;
	public Follow Follower {get{return 
	follower;} set{follower = value;}}
	
	// a unique identification number assigned by the flock manager 
	private int index = -1;
	public int Index {
		get { return index; }
		set { index = value; }
	}
	
	// get a reference to the manager's FlockManager component (script)
	public void setGameManager (GameObject gManager)
	{
		gameManager = gManager.GetComponent<GameManager> ();
	}
	
	//movement variables
	private float gravity = 200.0f;
	private Vector3 moveDirection;

	//steering variable
	private Vector3 steeringForce;
	private bool leaderFollowBool;

	//list of nearby flockers
	private List<GameObject> nearVillagers = new List<GameObject> ();
	private List<float> nearVillagersDistances = new List<float> ();
	
	//Creation of Villager
	public void Start ()
	{
		//get component references
		characterController = gameObject.GetComponent<CharacterController> ();
		steering = gameObject.GetComponent<Steering> ();
		
		leaderFollowBool = false;
		
		gameManager = GameManager.Instance;
	}
	
	//Handles Collision with Cart for Scoring and Clean Up Purposes
	public void OnCollisionEnter(Collision wCollision)
	{
		if(wCollision.gameObject.tag == "Cart")
		{
			GameObject savedVillager = this.gameObject;
			Villager safe = this; 
			gameManager.Villagers.Remove(savedVillager);
			gameManager.vFollowers.Remove(follower.gameObject);
			gameManager.Followers.Remove(safe);
			Destroy(follower.gameObject);
			Destroy(follower);
			Destroy(savedVillager);
			Destroy(this);
			gameManager.createNewVillager();
			gameManager.Saved.SavedVillagers = gameManager.Saved.SavedVillagers + 1;
			
			Destroy(savedVillager);	
			
			
		}
	}
		
		// Update is called once per frame
	public void Update ()
	{
		CalcSteeringForce ();
		ClampSteering ();
		
		moveDirection = transform.forward * steering.Speed;
		// movedirection equals velocity
		//add acceleration
		moveDirection += steeringForce * Time.deltaTime;
		//update speed
		steering.Speed = moveDirection.magnitude;
		if (steering.Speed != moveDirection.magnitude) {
			moveDirection = moveDirection.normalized * steering.Speed;
		}
		//orient transform
		if (moveDirection != Vector3.zero)
			transform.forward = moveDirection;
		
		// Apply gravity
		moveDirection.y -= gravity;
		
		// the CharacterController moves us subject to physical constraints
		characterController.Move (moveDirection * Time.deltaTime);
	}
	
	//Uses the various Movement Behaviors to calculate the vector to
	// determine the next position of the agent
	private void CalcSteeringForce ()
	{
		steeringForce = Vector3.zero;
		
		for(int i = 0; i < gameManager.Werewolves.Count; i++)
		{
			
			float wDist =  Vector3.Distance(this.transform.position, gameManager.Werewolves[i].transform.position);
			
			if( wDist < 20)
			{
				if(wDist < 5)
				{
					steeringForce += steering.Flee(gameManager.Werewolves[i].transform.position);
					
					if(leaderFollowBool == true)
					{
						gameManager.Followers.Remove(this);	
					}
						
					
					leaderFollowBool = false;
				}
				else
				{
					steeringForce += steering.Evasion(gameManager.Werewolves[i].transform.position 
						+ gameManager.Werewolves[i].transform.forward);
				}
			}
			else if(Vector3.Distance(this.transform.position, gameManager.Mayor.transform.position) < 40 && leaderFollowBool == false)
			{
				gameManager.Followers.Add(this);
				steeringForce += 10 * leaderFollow();
				steeringForce += gameManager.separationWt * Separation();
				steeringForce += gameManager.cohesionWt * Cohesion();
			}
			else if(leaderFollowBool == true)
			{
				steeringForce += 15 * leaderFollow();
				steeringForce += gameManager.separationWt * Separation();
				steeringForce += gameManager.cohesionWt * Cohesion();
			}
			else
			{	
				steeringForce += 2 * wander();
			}
		}
		
		steeringForce += gameManager.inBoundsWt * StayInBounds (200, new Vector3 (469, 0, 454));
		
		//avoid close obstacles
		for(int i =0; i < gameManager.Obstacles.Length; i++)
		{
			if(Vector3.Distance(this.transform.position, gameManager.Obstacles[i].transform.position) < 60)
			{
				//steeringForce += steering.AvoidObstacle(gameManager.Obstacles[i], gameManager.avoidDist);	
			}
		}
	}

	
	//Movement AI Behaviors -----------------------------------------------------------------------
	
	// tether type containment - not very good!
	private Vector3 StayInBounds ( float radius, Vector3 center)
	{
		
		steeringForce = Vector3.zero;
		
		if(transform.position.x > 750)
		{
			steeringForce += steering.Flee(new Vector3(800,0,transform.position.z));
		}
		
		if(transform.position.x < 200)
		{
			steeringForce += steering.Flee(new Vector3(150,0,transform.position.z));
		}
		
		if(transform.position.z > 715)
		{
			steeringForce += steering.Flee(new Vector3(transform.position.x,0,765));
		}
		
		if(transform.position.z < 205)
		{
			steeringForce += steering.Flee(new Vector3(transform.position.x,0,155));
		}
		
		if(transform.position.x > 750 || transform.position.x < 200 || 
			transform.position.z > 715 || transform.position.z < 205)
		{
			steeringForce += steering.Seek(gameManager.gameObject);
		}
		
		return steeringForce;
	}
	
	private Vector3 Cohesion ()
	{
		
		return steering.Arrival (gameManager.Mayor.transform.position);
	}
	
	private Vector3 Separation ()
	{
		//empty our lists
		nearVillagers.Clear ();
		nearVillagersDistances.Clear ();
		
		//method variables
		Vector3 dv = new Vector3(); // the desired velocity
		Vector3 sum = new Vector3();
		
		for(int i = 0; i < gameManager.Villagers.Count; i++)
		{
			//retireves distance between two flockers of reference numbers
			// findFlocker and i
			
			GameObject villager = gameManager.Villagers[i];
			
			float dist = Vector3.Distance(this.transform.position, gameManager.Villagers[i].transform.position);
			
			if(dist < 10.0 && dist != 0)
			{
				dv =  this.transform.position - villager.transform.position;
				
				dv.Normalize();
				
				dv = dv * ((1.0f/dist));
				sum += dv;
			}
		}
		
		float dist2 = Vector3.Distance(this.transform.position, gameManager.Mayor.transform.position);
		
		if(dist2 <= 10.0 && dist2 != 0)
		{
			dv = this.transform.position - gameManager.Mayor.transform.position;
			
			dv.Normalize();
			
			dv = dv * ((1.0f/dist2));
			
			sum += dv;
		}
		
		
		//sum.Normalize();
		//sum = sum * (steering.maxSpeed);
		sum = sum - this.steering.Velocity;

		return steering.AlignTo(sum);
	}

	private Vector3 wander()
	{

		steeringForce = Vector3.zero;

		Vector3 distance = transform.forward*2;// distance
		Vector3 refer = new Vector3(this.transform.position.x + distance.x,0,this.transform.position.z + distance.z);
		Vector3 wanderForce = Vector3.forward * radiusOfCircle;
		wanderForce = Quaternion.AngleAxis(_wanAngle, Vector3.up) * wanderForce;
		_wanAngle +=  Random.Range(0, 2 * _wanChange) - _wanChange;
		refer = refer + wanderForce;

		steeringForce += steering.Seek(refer);

		return steeringForce;

	}	
	
	private Vector3 leaderFollow()
	{
		steeringForce = Vector3.zero;
	
		
		if(gameManager.Followers[0] == this || gameManager.Followers[0] == null)
		{

			steeringForce += steering.Arrival(gameManager.Mayor.transform.position);	
		}
		else
		{
			
			steeringForce += steering.Arrival(gameManager.Followers[gameManager.Followers.Count-1].transform.position);
		}
		
		return steeringForce;
	}
	
	private Vector3 runAway()
	{
		
		steeringForce = Vector3.zero;
		
		for(int i = 0; i < gameManager.Werewolves.Count; i++)
		{
			if(Vector3.Distance(gameManager.Werewolves[i].transform.position, this.transform.position) < 80)
			{
				steeringForce += steering.Evasion(gameManager.Werewolves[i].transform.position);	
			}
			else
			{
				steeringForce += Vector3.zero;	
			}
		}
		
		for(int i = 0; i < gameManager.Werewolves.Count; i++)
		{
			if(Vector3.Distance(gameManager.Werewolves[i].transform.position, this.transform.position) < 20)
			{
				steeringForce += steering.Flee(gameManager.Werewolves[i]);	
			}
			else
			{
				steeringForce += Vector3.zero;
			}
		}
		
		return steeringForce;
	}

	private void ClampSteering ()
	{
		if (steeringForce.magnitude > steering.maxForce) {
			steeringForce.Normalize ();
			steeringForce *= steering.maxForce;
		}
	}
	
	//---------------------------------------------------------------------------------------------
	


	
	
}